#!/usr/bin/env python3
"""
GOOSE Rule Converter: Python to P4 (Versão Corrigida)
Converte regras de detecção de anomalias GOOSE IEC 61850
de funções Python para código P4 compilável.
"""

import re
import ast
from typing import Dict, List, Tuple, Any
from pathlib import Path


class PythonToP4Converter:
    """Conversor de regras Python para código P4 compilável."""

    def __init__(self):
        self.rules = []
        self.p4_template = self._load_p4_template()

        # Mapeamento de campos Python -> campos P4 corretos
        self.field_mapping = {
            'SqNum': 'hdr.goose.sqnum',
            'StNum': 'hdr.goose.stnum',
            'sqNum': 'hdr.goose.sqnum',
            'stNum': 'hdr.goose.stnum',
            'sq_num': 'hdr.goose.sqnum',
            'st_num': 'hdr.goose.stnum',
            'sqDiff': 'meta.sqdiff',
            'sq_diff': 'meta.sqdiff',
            'stDiff': 'meta.stdiff',
            'st_diff': 'meta.stdiff',
            'tDiff': 'meta.tdiff',
            't_diff': 'meta.tdiff',
            'timestampDiff': 'meta.timestamp_diff',
            'timestamp_diff': 'meta.timestamp_diff',
            'timeFromLastChange': '((bit<64>)meta.last_arrival_time - (bit<64>)meta.last_change_time)',
            'time_from_last_change': '((bit<64>)meta.last_arrival_time - (bit<64>)meta.last_change_time)',
            'cbStatus': 'hdr.goose.status',
            'cb_status': 'hdr.goose.status',
            'status': 'hdr.goose.status',
        }

    def _load_p4_template(self) -> str:
        """Retorna o template base do código P4 já compilável."""
        return '''/* GOOSE IEC 61850 Anomaly Detection - Complete Rules */
/* Auto-generated by Python to P4 Converter */

#include <core.p4>
#include <v1model.p4>

/* Ethernet Header */
header ethernet_t {
    bit<48> dst_addr;
    bit<48> src_addr;
    bit<16> ethertype;
}

/* GOOSE Header */
header goose_t {
    bit<16> appid;
    bit<16> reserved;
    bit<32> stnum;
    bit<32> sqnum;
    bit<64> timestamp;
    bit<8>  status;
    bit<24> padding;
}

/* Metadata */
struct metadata {
    bit<32> sqdiff;
    bit<32> stdiff;
    bit<32> tdiff;
    bit<32> timestamp_diff;
    bit<32> last_stnum;
    bit<32> last_sqnum;
    bit<64> last_timestamp;
    bit<48> last_arrival_time;
    bit<48> last_change_time;
    bit<1>  state_valid;
    bit<1>  is_first;
    bit<1>  stdiff_negative;
    bit<1>  tdiff_negative;
}

struct headers {
    ethernet_t ethernet;
    goose_t    goose;
}

/* Parser */
parser MyParser(packet_in packet,
                out headers hdr,
                inout metadata meta,
                inout standard_metadata_t standard_metadata) {
    state start {
        packet.extract(hdr.ethernet);
        transition select(hdr.ethernet.ethertype) {
            0x88B8: parse_goose;
            default: accept;
        }
    }
    state parse_goose {
        packet.extract(hdr.goose);
        transition accept;
    }
}

control MyVerifyChecksum(inout headers hdr, inout metadata meta) {
    apply { }
}

control MyIngress(inout headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {

    action update_state() {
        meta.last_arrival_time = standard_metadata.ingress_global_timestamp;

        if (meta.state_valid == 1) {
            if (hdr.goose.sqnum >= meta.last_sqnum) {
                meta.sqdiff = hdr.goose.sqnum - meta.last_sqnum;
            } else {
                meta.sqdiff = meta.last_sqnum - hdr.goose.sqnum;
            }

            if (hdr.goose.stnum >= meta.last_stnum) {
                meta.stdiff = hdr.goose.stnum - meta.last_stnum;
                meta.stdiff_negative = 0;
            } else {
                meta.stdiff = meta.last_stnum - hdr.goose.stnum;
                meta.stdiff_negative = 1;
            }

            if (hdr.goose.timestamp >= meta.last_timestamp) {
                meta.tdiff = (bit<32>)(hdr.goose.timestamp - meta.last_timestamp);
                meta.tdiff_negative = 0;
            } else {
                meta.tdiff = (bit<32>)(meta.last_timestamp - hdr.goose.timestamp);
                meta.tdiff_negative = 1;
            }

            if ((bit<64>)meta.last_arrival_time >= hdr.goose.timestamp) {
                meta.timestamp_diff = (bit<32>)((bit<64>)meta.last_arrival_time - hdr.goose.timestamp);
            } else {
                meta.timestamp_diff = (bit<32>)(hdr.goose.timestamp - (bit<64>)meta.last_arrival_time);
            }

            if (hdr.goose.stnum != meta.last_stnum) {
                meta.last_change_time = standard_metadata.ingress_global_timestamp;
            }
        } else {
            meta.state_valid = 1;
            meta.is_first = 1;
            meta.sqdiff = 0;
            meta.stdiff = 0;
            meta.tdiff = 0;
            meta.timestamp_diff = 0;
            meta.stdiff_negative = 0;
            meta.tdiff_negative = 0;
            meta.last_change_time = standard_metadata.ingress_global_timestamp;
        }

        meta.last_stnum = hdr.goose.stnum;
        meta.last_sqnum = hdr.goose.sqnum;
        meta.last_timestamp = hdr.goose.timestamp;
    }

    action drop_packet() {
        mark_to_drop(standard_metadata);
    }

    apply {
        if (hdr.goose.isValid()) {
            update_state();

            // ============================================
            // REGRAS DE DETECÇÃO GERADAS
            // ============================================

__RULES_PLACEHOLDER__

        }
    }
}

control MyEgress(inout headers hdr,
                 inout metadata meta,
                 inout standard_metadata_t standard_metadata) {
    apply { }
}

control MyComputeChecksum(inout headers hdr, inout metadata meta) {
    apply { }
}

control MyDeparser(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr.ethernet);
        packet.emit(hdr.goose);
    }
}

V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
'''

    def parse_python_file(self, filepath: str) -> List[Dict[str, Any]]:
        """Faz o parsing do arquivo Python e extrai as regras."""
        rules = []

        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        tree = ast.parse(content)

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                if node.name.startswith('rule_'):
                    rule_info = self._extract_rule_info(node)
                    if rule_info and rule_info['conditions']:
                        rules.append(rule_info)

        return rules

    def _extract_rule_info(self, func_node: ast.FunctionDef) -> Dict[str, Any]:
        """Extrai informações de uma função de regra."""
        rule_info = {
            'name': func_node.name,
            'docstring': ast.get_docstring(func_node) or '',
            'conditions': []
        }

        # Procura pelo return statement
        for node in ast.walk(func_node):
            if isinstance(node, ast.Return):
                if isinstance(node.value, ast.BoolOp) and isinstance(node.value.op, ast.And):
                    for value in node.value.values:
                        condition = self._parse_condition(value)
                        if condition:
                            rule_info['conditions'].append(condition)
                elif isinstance(node.value, ast.Compare):
                    condition = self._parse_condition(node.value)
                    if condition:
                        rule_info['conditions'].append(condition)

        rule_info['category'] = self._extract_category(rule_info['name'])
        return rule_info

    def _parse_condition(self, node: ast.AST) -> Dict[str, Any]:
        """Parse uma condição individual."""
        if isinstance(node, ast.Compare):
            if isinstance(node.left, ast.Name):
                field_name = node.left.id
                op = type(node.ops[0]).__name__
                if isinstance(node.comparators[0], ast.Constant):
                    value = node.comparators[0].value
                    return {
                        'field': field_name,
                        'operator': self._convert_operator(op),
                        'value': value
                    }
        return None

    def _convert_operator(self, py_op: str) -> str:
        """Converte operador Python para P4."""
        mapping = {
            'Lt': '<',
            'Gt': '>',
            'LtE': '<=',
            'GtE': '>=',
            'Eq': '==',
            'NotEq': '!='
        }
        return mapping.get(py_op, py_op)

    def _extract_category(self, rule_name: str) -> str:
        """Extrai a categoria do ataque pelo nome da regra."""
        categories = [
            'grayhole', 'high_StNum', 'injection', 'inverse_replay',
            'masquerade_fake_fault', 'masquerade_fake_normal',
            'poisoned_high_rate', 'random_replay'
        ]
        for category in categories:
            if category in rule_name:
                return category
        return 'unknown'

    def _convert_field(self, field_name: str) -> str:
        """Converte nome do campo Python para P4."""
        return self.field_mapping.get(field_name, f'UNKNOWN_{field_name}')

    def _convert_time_value(self, field_name: str, value) -> str:
        """Converte valores de tempo para P4."""
        if isinstance(value, float):
            if field_name in ['timestampDiff', 'timestamp_diff', 'tDiff', 't_diff']:
                return str(int(value * 1000)) if value < 100 else str(int(value))
            return str(int(value))
        return str(value)

    def _generate_p4_condition(self, condition: Dict[str, Any]) -> str:
        """Gera a condição P4 para uma regra."""
        field = self._convert_field(condition['field'])
        operator = condition['operator']
        value = self._convert_time_value(condition['field'], condition['value'])

        # Tratamento especial para valores negativos
        if condition['value'] < 0:
            if condition['field'] in ['stDiff', 'st_diff']:
                abs_value = abs(condition['value'])
                return f"(meta.stdiff_negative == 1 && meta.stdiff > {abs_value})"
            elif condition['field'] in ['tDiff', 't_diff']:
                abs_value = abs(condition['value'])
                return f"(meta.tdiff_negative == 1 && meta.tdiff > {abs_value})"

        # Verifica se o campo é conhecido
        if 'UNKNOWN' in field:
            return None

        return f"({field} {operator} {value})"

    def generate_p4_code(self, rules: List[Dict]) -> str:
        """Gera o código P4 completo com as regras."""
        rules_code = []
        rule_id = 1
        is_first_rule = True

        for rule in rules:
            # Gera comentário
            rules_code.append("            // ============================================")
            rules_code.append(f"            // {rule['name']}")
            if rule['docstring']:
                docstring = rule['docstring'].replace('\n', ' ')[:80]
                rules_code.append(f"            // {docstring}")
            rules_code.append("            // ============================================")

            # Gera condições
            conditions = []
            for condition in rule['conditions']:
                cond_str = self._generate_p4_condition(condition)
                if cond_str and 'UNKNOWN' not in cond_str:
                    conditions.append(cond_str)

            if conditions:
                # Define o prefixo
                if is_first_rule:
                    prefix = "            if "
                    is_first_rule = False
                else:
                    prefix = "            else if "

                # Monta a condição completa
                condition_block = " && ".join(conditions)

                # Adiciona a regra - CORRIGIDO: sem o ')' dentro do f-string
                rules_code.append(f"{prefix}({condition_block}) {{")
                rules_code.append("                drop_packet();")
                rules_code.append("            }")
                rules_code.append("")
                rule_id += 1

        # Se nenhuma regra foi gerada, adiciona um placeholder
        if not rules_code:
            rules_code = [
                "            // Nenhuma regra foi gerada",
                "            // Verifique o arquivo de entrada",
                "            if (1 == 0) { }"
            ]

        return self.p4_template.replace('__RULES_PLACEHOLDER__', '\n'.join(rules_code))

    def convert_file(self, input_file: str, output_file: str = None) -> str:
        """Converte um arquivo Python de regras para P4."""
        if output_file is None:
            output_file = str(Path(input_file).with_suffix('.p4'))

        print(f"📖 Convertendo {input_file} -> {output_file}")

        # Parse das regras
        rules = self.parse_python_file(input_file)

        if not rules:
            print("⚠️ Nenhuma regra encontrada no arquivo!")
            return ""

        categories = set(r['category'] for r in rules)
        print(f"✅ Encontradas {len(rules)} regras em {len(categories)} categorias")

        # Mostra categorias encontradas
        for cat in categories:
            count = len([r for r in rules if r['category'] == cat])
            print(f"   - {cat}: {count} regra(s)")

        # Gera código P4
        p4_code = self.generate_p4_code(rules)

        # Salva arquivo
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(p4_code)

        print(f"✅ Arquivo P4 gerado: {output_file}")

        # Verifica se o arquivo gerado tem conteúdo válido
        if len(p4_code) < 1000:
            print("⚠️ O arquivo gerado parece muito pequeno, verifique se as regras foram convertidas corretamente.")

        return p4_code


def main():
    """Função principal."""
    import argparse

    parser = argparse.ArgumentParser(
        description='Converte regras de detecção GOOSE de Python para P4'
    )
    parser.add_argument('input', help='Arquivo Python com as regras')
    parser.add_argument('-o', '--output', help='Arquivo P4 de saída (opcional)')
    parser.add_argument('-v', '--verbose', action='store_true',
                       help='Mostrar informações detalhadas')

    args = parser.parse_args()

    converter = PythonToP4Converter()

    try:
        p4_code = converter.convert_file(args.input, args.output)

        if args.verbose and p4_code:
            print("\n" + "="*60)
            print("PRÉ-VISUALIZAÇÃO DO CÓDIGO GERADO")
            print("="*60)
            # Mostra apenas a parte das regras
            lines = p4_code.split('\n')
            in_rules = False
            for i, line in enumerate(lines):
                if 'REGRAS DE DETECÇÃO GERADAS' in line:
                    in_rules = True
                    continue
                if in_rules:
                    if '}' in line and i < len(lines)-1 and 'apply' in lines[i+1]:
                        break
                    print(line)

    except Exception as e:
        print(f"❌ Erro durante a conversão: {e}")
        import traceback
        traceback.print_exc()
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
