/* GOOSE IEC 61850 Anomaly Detection - Complete Rules */
/* Auto-generated by Python to P4 Converter */

#include <core.p4>
#include <v1model.p4>

/* Ethernet Header */
header ethernet_t {
    bit<48> dst_addr;
    bit<48> src_addr;
    bit<16> ethertype;
}

/* GOOSE Header */
header goose_t {
    bit<16> appid;
    bit<16> reserved;
    bit<32> stnum;
    bit<32> sqnum;
    bit<64> timestamp;
    bit<8>  status;
    bit<24> padding;
}

/* Metadata */
struct metadata {
    bit<32> sqdiff;
    bit<32> stdiff;
    bit<32> tdiff;
    bit<32> timestamp_diff;
    bit<32> last_stnum;
    bit<32> last_sqnum;
    bit<64> last_timestamp;
    bit<48> last_arrival_time;
    bit<48> last_change_time;
    bit<1>  state_valid;
    bit<1>  is_first;
    bit<1>  stdiff_negative;
    bit<1>  tdiff_negative;
}

struct headers {
    ethernet_t ethernet;
    goose_t    goose;
}

/* Parser */
parser MyParser(packet_in packet,
                out headers hdr,
                inout metadata meta,
                inout standard_metadata_t standard_metadata) {
    state start {
        packet.extract(hdr.ethernet);
        transition select(hdr.ethernet.ethertype) {
            0x88B8: parse_goose;
            default: accept;
        }
    }
    state parse_goose {
        packet.extract(hdr.goose);
        transition accept;
    }
}

control MyVerifyChecksum(inout headers hdr, inout metadata meta) {
    apply { }
}

control MyIngress(inout headers hdr,
                  inout metadata meta,
                  inout standard_metadata_t standard_metadata) {

    action update_state() {
        meta.last_arrival_time = standard_metadata.ingress_global_timestamp;

        if (meta.state_valid == 1) {
            if (hdr.goose.sqnum >= meta.last_sqnum) {
                meta.sqdiff = hdr.goose.sqnum - meta.last_sqnum;
            } else {
                meta.sqdiff = meta.last_sqnum - hdr.goose.sqnum;
            }

            if (hdr.goose.stnum >= meta.last_stnum) {
                meta.stdiff = hdr.goose.stnum - meta.last_stnum;
                meta.stdiff_negative = 0;
            } else {
                meta.stdiff = meta.last_stnum - hdr.goose.stnum;
                meta.stdiff_negative = 1;
            }

            if (hdr.goose.timestamp >= meta.last_timestamp) {
                meta.tdiff = (bit<32>)(hdr.goose.timestamp - meta.last_timestamp);
                meta.tdiff_negative = 0;
            } else {
                meta.tdiff = (bit<32>)(meta.last_timestamp - hdr.goose.timestamp);
                meta.tdiff_negative = 1;
            }

            if ((bit<64>)meta.last_arrival_time >= hdr.goose.timestamp) {
                meta.timestamp_diff = (bit<32>)((bit<64>)meta.last_arrival_time - hdr.goose.timestamp);
            } else {
                meta.timestamp_diff = (bit<32>)(hdr.goose.timestamp - (bit<64>)meta.last_arrival_time);
            }

            if (hdr.goose.stnum != meta.last_stnum) {
                meta.last_change_time = standard_metadata.ingress_global_timestamp;
            }
        } else {
            meta.state_valid = 1;
            meta.is_first = 1;
            meta.sqdiff = 0;
            meta.stdiff = 0;
            meta.tdiff = 0;
            meta.timestamp_diff = 0;
            meta.stdiff_negative = 0;
            meta.tdiff_negative = 0;
            meta.last_change_time = standard_metadata.ingress_global_timestamp;
        }

        meta.last_stnum = hdr.goose.stnum;
        meta.last_sqnum = hdr.goose.sqnum;
        meta.last_timestamp = hdr.goose.timestamp;
    }

    action drop_packet() {
        mark_to_drop(standard_metadata);
    }

    apply {
        if (hdr.goose.isValid()) {
            update_state();

            // ============================================
            // REGRAS DE DETECÇÃO GERADAS
            // ============================================

            // ============================================
            // rule_grayhole_sqnum_tdiff
            // Detect low SqNum combined with high tDiff.
            // ============================================
            if ((hdr.goose.sqnum < 5) && (meta.tdiff > 1500)) {
                drop_packet();
            }

            // ============================================
            // rule_grayhole_sqnum_stnum
            // Detect low SqNum together with abnormally low StNum.
            // ============================================
            else if ((hdr.goose.sqnum < 5) && (hdr.goose.stnum < 30)) {
                drop_packet();
            }

            // ============================================
            // rule_grayhole_sqnum_stdiff
            // Detect low SqNum combined with unusually high stDiff.
            // ============================================
            else if ((hdr.goose.sqnum < 5) && (meta.stdiff > 500)) {
                drop_packet();
            }

            // ============================================
            // rule_grayhole_persistent
            // Detect sustained low SqNum with long time since last change.
            // ============================================
            else if ((hdr.goose.sqnum <= 4) && (meta.timestamp_diff <= 200) && (((bit<64>)meta.last_arrival_time - (bit<64>)meta.last_change_time) > 100)) {
                drop_packet();
            }

            // ============================================
            // rule_high_StNum_state
            // Retorna True se o pacote for suspeito de high_StNum baseado em StNum e stDiff.
            // ============================================
            // ============================================
            // rule_high_StNum_seq_time
            // Retorna True se o pacote for suspeito de high_StNum baseado em SqNum, sqDiff, tD
            // ============================================
            // ============================================
            // rule_injection_seq
            // Detect injection based on abnormal sequence numbers.
            // ============================================
            else if ((hdr.goose.sqnum > 80) && (meta.sqdiff > 100)) {
                drop_packet();
            }

            // ============================================
            // rule_injection_state
            // Detect injection based on abnormal state numbers and status.
            // ============================================
            else if ((hdr.goose.stnum < 20) && (hdr.goose.status > 1)) {
                drop_packet();
            }

            // ============================================
            // rule_inverse_replay_time_delay
            // Retorna True se o pacote apresentar indícios de inverse replay via tempo.
            // ============================================
            else if ((meta.tdiff > 2500)) {
                drop_packet();
            }

            // ============================================
            // rule_inverse_replay_status_jump
            // Retorna True se o pacote apresentar indícios de inverse replay via contadores.
            // ============================================
            else if ((hdr.goose.stnum < 30) && (meta.stdiff > 400)) {
                drop_packet();
            }

            // ============================================
            // rule_masquerade_fake_fault_tdiff_ts
            // Detect masquerade_fake_fault using high tDiff and timestampDiff.
            // ============================================
            else if ((meta.tdiff > 1000)) {
                drop_packet();
            }

            // ============================================
            // rule_masquerade_fake_fault_tdiff_stdiff
            // Detect masquerade_fake_fault using high tDiff combined with large stDiff.
            // ============================================
            else if ((meta.tdiff > 1000) && (meta.stdiff > 300)) {
                drop_packet();
            }

            // ============================================
            // rule_masquerade_fake_fault_sqnum_ts
            // Detect masquerade_fake_fault using low sqNum together with elevated timestampDif
            // ============================================
            else if ((hdr.goose.sqnum < 10)) {
                drop_packet();
            }

            // ============================================
            // rule_masquerade_fake_fault_lowstnum_cbstatus
            // Detect masquerade_fake_fault using unusually low StNum and constant closed break
            // ============================================
            else if ((hdr.goose.stnum < 200) && (hdr.goose.status == 1)) {
                drop_packet();
            }

            // ============================================
            // rule_masquerade_fake_normal_state_and_stdiff
            // Retorna True se o pacote for suspeito de masquerade_fake_normal.
            // ============================================
            else if ((hdr.goose.stnum > 800) && (meta.stdiff > 500)) {
                drop_packet();
            }

            // ============================================
            // rule_masquerade_fake_normal_state_and_timestampdiff
            // Retorna True se o pacote for suspeito de masquerade_fake_normal.
            // ============================================
            else if ((hdr.goose.stnum > 800) && (meta.timestamp_diff > 400)) {
                drop_packet();
            }

            // ============================================
            // rule_poisoned_high_rate_state
            // Retorna True se o pacote apresentar indícios de poisoned_high_rate via estado pr
            // ============================================
            // ============================================
            // rule_poisoned_high_rate_timing
            // Retorna True se o pacote apresentar indícios de poisoned_high_rate via anomalias
            // ============================================
            // ============================================
            // rule_random_replay_sqnum_stnum
            // High sequence number together with unusually low state number.
            // ============================================
            else if ((hdr.goose.sqnum > 55) && (hdr.goose.stnum < 100)) {
                drop_packet();
            }

            // ============================================
            // rule_random_replay_sqdiff_stdiff
            // Large jump in sequence diff combined with extreme negative state diff.
            // ============================================
            else if ((meta.sqdiff > 30)) {
                drop_packet();
            }

            // ============================================
            // rule_random_replay_timestamp_timechange
            // Timestamp far from arrival time and long interval since last change.
            // ============================================

        }
    }
}

control MyEgress(inout headers hdr,
                 inout metadata meta,
                 inout standard_metadata_t standard_metadata) {
    apply { }
}

control MyComputeChecksum(inout headers hdr, inout metadata meta) {
    apply { }
}

control MyDeparser(packet_out packet, in headers hdr) {
    apply {
        packet.emit(hdr.ethernet);
        packet.emit(hdr.goose);
    }
}

V1Switch(MyParser(), MyVerifyChecksum(), MyIngress(), MyEgress(), MyComputeChecksum(), MyDeparser()) main;
